##################################################################
# Parameters file. Should follow the syntax defined in:  
# http://docs.ansible.com/ansible/latest/YAMLSyntax.html
# More general reference: http://www.yaml.org/spec/1.2/spec.html

message: 'Hello World!'
sleeptime: 2