#!/usr/bin/env python3

import argparse
import time

from utils import setup_logger, load_yml


def run(config_file):
    """Run hello world pipeline.

    Args:
        config_file (str): hello world parameters
    """

    logger = setup_logger(name="hello-world")

    start_time_full = time.time()

    # Loading configurations
    pipe_config = load_yml(config_file)
    param = pipe_config.get("inputs")
    logger.info("Parameters: %s", param)

    time.sleep(5)  # Simulating some work being done

    message = param.get("message", "Hello, World!")

    logger.info("Message: %s", message)
    logger.info("Time elapsed: %s", str(time.time() - start_time_full))


if __name__ == "__main__":
    # Create the parser and add arguments
    parser = argparse.ArgumentParser()
    parser.add_argument(dest="config_path", help="yaml config path")

    args = parser.parse_args()
    config_path = args.config_path

    # Run pipeline
    run(config_path)
