# Generated by Django 5.0.3 on 2024-03-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_process_release_alter_process_used_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="worker",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
