# Generated by Django 5.0.3 on 2024-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_process_used_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="used_config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
