# Generated by Django 5.0.3 on 2024-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_process_used_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="pid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
