# Generated by Django 5.1.1 on 2026-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Successful'), (1, 'Pending'), (2, 'Running'), (3, 'Stopping'), (4, 'Stopped'), (5, 'Failed'), (6, 'Queued')], default=6, verbose_name='Status'),
        ),
    ]
